apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-service
  template:
    metadata:
      labels:
        app: aws-service
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
        - name: aws-service
          image: localstack/localstack:3.0.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 4566
---
apiVersion: v1
kind: Service
metadata:
  name: aws-service
  labels:
    app: aws-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 4566
      targetPort: 4566
  selector:
    app: aws-service